name: common-wheel-build
description: Common wheel build and install

inputs:
  python-version:
    description: The Python version to setup
    required: true

# This action runs for linux and macos only
runs:
  using: "composite"
  steps:
    # > --------------------------------------------------
    # > Build
    # - name: Update env vars
    #   run: |
    #     echo 'CARGO_BUILD_TARGET=${{ matrix.target-arch }}' >> $GITHUB_ENV
    #     echo 'RUSTFLAGS=-C target-cpu=${{ matrix.target-cpu }}' >> $GITHUB_ENV

    # - name: Print env vars
    #   run: |
    #     env | sort

    - name: Replace `build.py`
      shell: bash
      run: |
        cp scripts/build.py src/build.py

    - name: Set version
      shell: bash
      run: |
        # Format: {semver}.dev{date}+{build_number}.cpu.{target_cpu}
        # Example: 1.208.0.dev20251212+7001.cpu.sapphirerapids

        base_version=$(yq -r '.tool.poetry.version' src/pyproject.toml)
        target_cpu=${{ matrix.target-cpu }}

        dev_version="dev$(date -u +%Y%m%d)+${GITHUB_RUN_NUMBER}"
        release_version=${base_version}.${dev_version}
        local_version_cpu="cpu.${target_cpu}"

        if [ "${target_cpu}" == "generic" ]; then
          new_version="${release_version}"
        else
          new_version="${release_version}.${local_version_cpu}"
        fi

        poetry version --directory=src ${new_version}
        echo "RELEASE_VERSION=${release_version}" >> $GITHUB_ENV

        echo "Set version to ${new_version}"

    # - name: Install NautilusTrader
    #   run: |
    #     pushd src
    #     poetry install
    #     popd

    - name: Build NautilusTrader
      shell: bash
      run: |
        pushd src
        poetry build --format wheel
        popd

    - name: List dist
      shell: bash
      run: |
        tree src/dist

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: src/dist/*
        tag_name: v${{ env.RELEASE_VERSION }}
        name: v${{ env.RELEASE_VERSION }}
