name: "release"

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - nightly
      - develop
      - ci-init

# on:
#   repository_dispatch:
#     types: [on-demand-release]

jobs:
  publish-nautilus-trader:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    name: publish (${{ matrix.target-arch }} | ${{ matrix.target-cpu }})
    strategy:
      matrix:
        include:
          # > x86_64-unknown-linux-gnu
          - target-arch: x86_64-unknown-linux-gnu
            target-cpu: generic # 默认
          # - target-arch: x86_64-unknown-linux-gnu
          #   target-cpu: x86-64
          # - target-arch: x86_64-unknown-linux-gnu
          #   target-cpu: x86-64-v4
          # - target-arch: x86_64-unknown-linux-gnu
          #   target-cpu: cascadelake
          # - target-arch: x86_64-unknown-linux-gnu
          #   target-cpu: icelake-server
          # - target-arch: x86_64-unknown-linux-gnu
          #   target-cpu: skylake-avx512
          - target-arch: x86_64-unknown-linux-gnu
            target-cpu: sapphirerapids
          # - target-arch: x86_64-unknown-linux-gnu
          #   target-cpu: emeraldrapids
          # > aarch64-unknown-linux-gnu
          # - target-arch: aarch64-unknown-linux-gnu
          #   target-cpu: generic # 默认
          # - target-arch: aarch64-unknown-linux-gnu
          #   target-cpu: neoverse-n1 # Graviton2
          # - target-arch: aarch64-unknown-linux-gnu
          #   target-cpu: neoverse-v1 # Graviton3
          # - target-arch: aarch64-unknown-linux-gnu
          #   target-cpu: neoverse-v2 # Graviton4
    defaults:
      run:
        shell: bash
    env:
      BUILD_MODE: release
      # TARGET_ARCH: ${{ matrix.target-arch }}
      # TARGET_CPU: ${{ matrix.target-cpu }}
      # > --------------------------------------------------
      # > cargo
      CARGO_TARGET_DIR: ${{ github.workspace }}/.cache/cargo/target
      # CARGO_LOG: debug
      # CARGO_TERM_VERBOSE: true
      RUST_BACKTRACE: 1
      CARGO_BUILD_TARGET: ${{ matrix.target-arch }}
      RUSTFLAGS: -C target-cpu=${{ matrix.target-cpu }}
      # -Z tune-cpu=${{ matrix.target-cpu }} # the option `Z` is only accepted on the nightly compiler
      # > --------------------------------------------------
      # > sccache
      # https://github.com/Mozilla-Actions/sccache-action
      SCCACHE_IDLE_TIMEOUT: 0
      SCCACHE_DIRECT: "true"
      SCCACHE_CACHE_MULTIARCH: 1
      SCCACHE_DIR: ${{ github.workspace }}/.cache/sccache
      RUSTC_WRAPPER: "sccache"
      CC: "sccache clang"
      CXX: "sccache clang++"
      # Incrementally compiled crates cannot be cached by sccache
      # https://github.com/mozilla/sccache#rust
      CARGO_INCREMENTAL: 0
    steps:
      # > --------------------------------------------------
      # > OS
      - name: Install / Update OS dependencies
        run: |
          sudo apt install -y \
            curl \
            clang \
            git \
            libssl-dev \
            make \
            pkg-config \
            g++-aarch64-linux-gnu \
            gcc-aarch64-linux-gnu \
            binutils

      - name: Setup mold
        uses: rui314/setup-mold@v1

      # > --------------------------------------------------
      # > Repository
      - name: Checkout repository `self`
        uses: actions/checkout@v4

      - name: Checkout repository `nautilus_trader`
        uses: actions/checkout@v4
        with:
          repository: nautechsystems/nautilus_trader
          ref: develop
          path: src

      # > --------------------------------------------------
      # > Rust
      - name: Cached cargo
        uses: actions/cache@v4
        # https://doc.rust-lang.org/cargo/guide/cargo-home.html#caching-the-cargo-home-in-ci
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-

      - name: Set up Rust toolchain
        run: |
          rustup self update
          rustup target add ${{ matrix.target-arch }}
          rustup update --force stable
          rustup toolchain add \
            --component clippy,rustfmt \
            --profile minimal \
            stable

      # > --------------------------------------------------
      # > sccache
      - name: Cached sccache
        uses: actions/cache@v4
        with:
          path: ${{ env.SCCACHE_DIR }}
          key: sccache-${{ runner.os }}-${{ github.workflow }}-${{ github.job }}-${{ matrix.target-arch }}-${{ matrix.target-cpu }}-${{ hashFiles('**/Cargo.lock', '**/poetry.lock') }}
          restore-keys: |
            sccache-${{ runner.os }}-${{ github.workflow }}-${{ github.job }}-${{ matrix.target-arch }}-${{ matrix.target-cpu }}-
            sccache-${{ runner.os }}-${{ github.workflow }}-${{ github.job }}-${{ matrix.target-arch }}-
            sccache-${{ runner.os }}-${{ github.workflow }}-${{ github.job }}-
            sccache-${{ runner.os }}-${{ github.workflow }}-
            sccache-${{ runner.os }}-

      - name: Run sccache
        uses: mozilla-actions/sccache-action@v0.0.7

      # > --------------------------------------------------
      # > Python
      - name: Setup Python
        uses: actions/setup-python@v5
        id: python-install
        with:
          # python-version: "3.13"
          python-version-file: "src/pyproject.toml"
          # python-version-file: ".python-version"
          # cache: "poetry"

      # - name: Install uv
      #   uses: astral-sh/setup-uv@v5
      #   with:
      #     enable-cache: true

      - name: Update env vars
        run: |
          echo 'PIPX_DEFAULT_PYTHON=${{ steps.python-install.outputs.python-path }}' >> $GITHUB_ENV

      - name: Install poetry
        run: pipx install poetry

      # > --------------------------------------------------
      # > Debug
      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v3
      #   with:
      #     limit-access-to-actor: true

      # > --------------------------------------------------
      # > Build
      # - name: Update env vars
      #   run: |
      #     echo 'CARGO_BUILD_TARGET=${{ matrix.target-arch }}' >> $GITHUB_ENV
      #     echo 'RUSTFLAGS=-C target-cpu=${{ matrix.target-cpu }}' >> $GITHUB_ENV

      # - name: Print env vars
      #   run: |
      #     env | sort

      # - name: Install NautilusTrader
      #   run: |
      #     pushd src
      #     poetry install
      #     popd

      - name: Replace `build.py`
        run: |
          cp scripts/build.py src/build.py

      - name: Build NautilusTrader
        run: |
          pushd src
          # poetry install
          poetry build --format wheel
          popd

      - name: List dist
        run: |
          tree src/dist
