name: "release"

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - nightly
      - develop
      - ci-init

# on:
#   repository_dispatch:
#     types: [on-demand-release]

jobs:
  publish:
    permissions:
      contents: write
    name: publish ${{ matrix.os }} (${{ matrix.target-arch }} | ${{ matrix.target-cpu }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            target-arch: x86_64-unknown-linux-gnu
            target-cpu: generic
          - os: ubuntu-22.04
            target-arch: x86_64-unknown-linux-gnu
            target-cpu: sapphirerapids
          - os: ubuntu-24.04
            target-arch: x86_64-unknown-linux-gnu
            target-cpu: generic
          - os: ubuntu-24.04
            target-arch: x86_64-unknown-linux-gnu
            target-cpu: sapphirerapids
          - os: macos-latest
            target-arch: aarch64-apple-darwin
            target-cpu: generic
    env:
      TARGET_ARCH: ${{ matrix.target-arch }}
      TARGET_CPU: ${{ matrix.target-cpu }}
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repository `self`
        uses: actions/checkout@v4

      - name: common-setup
        uses: ./.github/actions/common-setup
        with:
          python-version: "3.12"

      # > --------------------------------------------------
      # > Repository
      - name: Checkout repository `nautilus_trader`
        uses: actions/checkout@v4
        with:
          repository: nautechsystems/nautilus_trader
          ref: develop
          path: src

      # > --------------------------------------------------
      # > Debug
      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v3
      #   with:
      #     limit-access-to-actor: true

      # - name: Debug
      #   run: |
      #     which yq
      #     yq --version

      - name: common-wheel-build
        uses: ./.github/actions/common-wheel-build
