name: "release"

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - nightly
      - develop
      - ci-init

# on:
#   repository_dispatch:
#     types: [on-demand-release]

jobs:
  publish-nautilus-trader:
    permissions:
      contents: write
    name: publish ${{ matrix.os }} (${{ matrix.arch-cpu.target-arch }} | ${{ matrix.arch-cpu.target-cpu }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-24.04
          - ubuntu-22.04
          # - macos-latest
        arch-cpu:
          # > x86_64-unknown-linux-gnu
          - target-arch: x86_64-unknown-linux-gnu
            target-cpu: generic # 默认
          # - target-arch: x86_64-unknown-linux-gnu
          #   target-cpu: x86-64
          # - target-arch: x86_64-unknown-linux-gnu
          #   target-cpu: x86-64-v4
          # - target-arch: x86_64-unknown-linux-gnu
          #   target-cpu: cascadelake
          # - target-arch: x86_64-unknown-linux-gnu
          #   target-cpu: icelake-server
          # - target-arch: x86_64-unknown-linux-gnu
          #   target-cpu: skylake-avx512
          - target-arch: x86_64-unknown-linux-gnu
            target-cpu: sapphirerapids
          # - target-arch: x86_64-unknown-linux-gnu
          #   target-cpu: emeraldrapids

          # > aarch64-unknown-linux-gnu
          # - target-arch: aarch64-unknown-linux-gnu
          #   target-cpu: generic # 默认
          # - target-arch: aarch64-unknown-linux-gnu
          #   target-cpu: neoverse-n1 # Graviton2
          # - target-arch: aarch64-unknown-linux-gnu
          #   target-cpu: neoverse-v1 # Graviton3
          # - target-arch: aarch64-unknown-linux-gnu
          #   target-cpu: neoverse-v2 # Graviton4
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repository `self`
        uses: actions/checkout@v4

      - name: common-setup
        uses: ./.github/actions/common-setup
        with:
          python-version: "3.12"

      # > --------------------------------------------------
      # > Repository
      - name: Checkout repository `nautilus_trader`
        uses: actions/checkout@v4
        with:
          repository: nautechsystems/nautilus_trader
          ref: develop
          path: src

      # > --------------------------------------------------
      # > Debug
      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v3
      #   with:
      #     limit-access-to-actor: true

      # - name: Debug
      #   run: |
      #     which yq
      #     yq --version

      - name: common-wheel-build
        uses: ./.github/actions/common-wheel-build
