name: "release"

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - nightly
      - develop
  # schedule:
  #   - cron: "0 0 * * *"

# on:
#   repository_dispatch:
#     types: [on-demand-release]

jobs:
  publish:
    permissions:
      contents: write
    name: publish (${{ matrix.os }} ${{ matrix.target-arch }} ${{ matrix.target-cpu }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          # > --------------------------------------------------
          # > Ubuntu 22.04
          - os: ubuntu-22.04
            target-arch: x86_64-unknown-linux-gnu
            target-cpu: generic
          - os: ubuntu-22.04
            target-arch: x86_64-unknown-linux-gnu
            target-cpu: sapphirerapids
          - os: ubuntu-22.04
            target-arch: x86_64-unknown-linux-gnu
            target-cpu: x86-64-v4
          # > --------------------------------------------------
          # > Ubuntu 24.04
          - os: ubuntu-24.04
            target-arch: x86_64-unknown-linux-gnu
            target-cpu: generic
          - os: ubuntu-24.04
            target-arch: x86_64-unknown-linux-gnu
            target-cpu: sapphirerapids
          - os: ubuntu-24.04
            target-arch: x86_64-unknown-linux-gnu
            target-cpu: x86-64-v4
          # > --------------------------------------------------
          # > macOS 15
          - os: macos-15
            target-arch: aarch64-apple-darwin
            target-cpu: "apple-m1" # 使用 `generic` 时，ring 无法编译 / `apple-m1`
          - os: macos-15-large
            target-arch: x86_64-apple-darwin
            target-cpu: "generic"
    env:
      TARGET_ARCH: ${{ matrix.target-arch }}
      TARGET_CPU: ${{ matrix.target-cpu }}
    defaults:
      run:
        shell: bash
    steps:
      # > --------------------------------------------------
      # > Repository
      - name: Checkout repository `self`
        uses: actions/checkout@v4

      - name: Checkout repository `nautilus_trader`
        uses: actions/checkout@v4
        id: nautilus-trader-checkout
        with:
          repository: nautechsystems/nautilus_trader
          ref: develop
          path: src

      # > --------------------------------------------------
      # > Common setup: 需放到 `checkout` 之后，才能正确生成 cache key
      - name: Common setup
        uses: ./.github/actions/common-setup
        with:
          python-version: "3.12"

      # > --------------------------------------------------
      # > Debug
      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v3
      #   with:
      #     limit-access-to-actor: true

      # - name: Debug
      #   run: |
      #     which yq
      #     yq --version

      - name: Common wheel build
        uses: ./.github/actions/common-wheel-build

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: src/dist/*
          tag_name: v${{ env.RELEASE_VERSION }}
          name: v${{ env.RELEASE_VERSION }}
          body: |
            NautilusTrader Commit: [${{ steps.nautilus-trader-checkout.outputs.commit }}](https://github.com/nautechsystems/nautilus_trader/commit/${{ steps.nautilus-trader-checkout.outputs.commit }})
