name: "release"

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - nightly
      - develop
      - ci-init

# on:
#   repository_dispatch:
#     types: [on-demand-release]

jobs:
  publish-nautilus-trader:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository `self`
        uses: actions/checkout@v4

      - name: Checkout repository `nautilus_trader``
        uses: actions/checkout@v4
        with:
          repository: nautechsystems/nautilus_trader
          ref: develop
          path: src

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          # python-version: "3.13"
          python-version-file: "src/pyproject.toml"
          # python-version-file: ".python-version"
          # cache: "poetry"

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Install poetry
        run: pipx install poetry
